# Generated by Django 4.2.2 on 2023-07-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_alter_lesson_options"),
        ("problems", "0002_alter_problem_options_problem_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="problem",
            name="in_lesson",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="problems",
                to="lessons.lesson",
            ),
        ),
    ]
