# Generated by Django 4.2.2 on 2023-07-07 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_alter_lesson_options"),
        ("problems", "0004_alter_problem_in_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="in_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="problems",
                to="lessons.lesson",
            ),
        ),
    ]
