# Generated by Django 4.2.2 on 2023-07-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0005_alter_problem_in_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="hint",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
