# Generated by Django 4.2.2 on 2023-07-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trycode", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trycode",
            name="identification",
            field=models.TextField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
