# Generated by Django 4.2.2 on 2023-07-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_alter_lesson_options"),
        ("trycode", "0002_trycode_identification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trycode",
            name="identification",
        ),
        migrations.AddField(
            model_name="trycode",
            name="description",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="trycode",
            name="in_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trycode",
                to="lessons.lesson",
            ),
        ),
        migrations.AddField(
            model_name="trycode",
            name="intro",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
