# Generated by Django 4.2.2 on 2023-07-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trycode", "0004_alter_trycode_description_alter_trycode_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="trycode",
            name="identification",
            field=models.IntegerField(default=0),
        ),
    ]
