# Generated by Django 4.2.2 on 2023-07-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trycode", "0005_trycode_identification"),
    ]

    operations = [
        migrations.AddField(
            model_name="trycode",
            name="summary",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
