# Generated by Django 4.2.2 on 2023-07-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trycode", "0006_trycode_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trycode",
            name="description",
        ),
    ]
