# Generated by Django 4.2.2 on 2023-07-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ("created_at",)},
        ),
    ]
